package commons.models;

public enum MessageType {
    CONNECT, GAME_STARTED, GAME_WAITING, LEADERBOARD, GAME_ENDED, DISCONNECT, CORRECT_ANSWER, WRONG_ANSWER, USER_EMOTE, START_GAME,
    MY_ANSWER, USER_JOINED, CONNECTED, QUESTION, TIME_JOKER, REMOVE_JOKER, DOUBLE_JOKER, TEST
}
